apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-app
  namespace: strapi-app
  labels:
    app: strapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi-app
  template:
    metadata:
      labels:
        app: strapi-app
    spec:
      containers:
      - name: strapi-app
        image: populardigitalai/strapi-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1337
          protocol: TCP
        env:
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "1337"
        envFrom:
          - configMapRef:
              name: strapi-app-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /
            port: 1337
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 6
