apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-app
  namespace: strapi-app
  labels:
    app: strapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi-app
  template:
    metadata:
      labels:
        app: strapi-app
    spec:
      containers:
      - name: strapi-app
        image: populardigitalai/strapi-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1337
          protocol: TCP
        env:
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "1337"
          - name: NODE_OPTIONS        # prevents JS OOM crashes
            value: "--max-old-space-size=2048"
        envFrom:
          - configMapRef:
              name: strapi-app-config

        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

        readinessProbe:
          httpGet:
            path: /_health
            port: 1337
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 6

        livenessProbe:
          httpGet:
            path: /_health
            port: 1337
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 6
